services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-debian
    volumes:
      - ./:/site
    working_dir: /site/src
    ports:
      - ${HUGO_SERVER_PORT:-1313}:${HUGO_SERVER_PORT:-1313}
    command: server --bind 0.0.0.0 --port ${HUGO_SERVER_PORT:-1313}
